cc_library(
    name = "galaxy_fs_internal_lib",
    visibility = ["//cpp/core:__subpackages__"],
    srcs = [
        "galaxy_fs_internal.h",
        "galaxy_fs_internal.cc",
    ],
    deps= [
        "@google_absl//absl/strings",
        "@google_glog//:glog"
    ]
)